### ISSUE TITLE
Plugin bagus

### ISSUE THREAD

**Issue by Kygekraqmak** [NaufalBlaze/RankInfoUI#1]
Mirip seperti [KygekRanksUI](https://poggit.pmmp.io/p/KygekRanksUI), tetapi belum support unlimited rank.

**Comment by NaufalBlaze** [comment]
Makasih, Sebenernya Ini Plugins Sudah Lama Dibuat, Tetapi Belum Dirilis Ke Poggit, Terima Kasih Telah Mencoba 👍

**Comment by Kygekraqmak** [comment]
Sama2

**Comment by NaufalBlaze** [comment]
Ada Whatsapp?
